### ISSUE TITLE
Image tapped is not image that I wanted

### ISSUE THREAD

**Issue by eeren323** [exyte/MediaPicker#17]
Hi, 

Amazing projects and libraries, it's been really helpful, many thanks ! 

However, with media picker 1.3.0, I am seeing issue on ios 16.6, where the image selected becomes the image below it when it gets loaded, feels like a boundary issue, will continue debugging and provide updates

**Comment by f3dm76** [comment]
Hey @X901, thank you very much for your suggestion, please check out version 1.4.0 - the issue should be gone there. Have a wonderful day!
