### ISSUE TITLE
Support for camera capture customization

### ISSUE THREAD

**Issue by roeekl** [exyte/MediaPicker#19]
Hi,
It would be great to have the option to customize the camera capture view itself. 

For example, I want to be able to first show the camera capture view, without the cancel button in the top left corner, and with gallery icon in the bottom left that will switch to the photo picker.

Right now this isn't an option as I can only change the preview screen.

**Comment by f3dm76** [comment]
Hey @roeekl, thank you for your suggestion, please check out version 2.1.0, I added cameraViewBuilder closure, parameter spec is in readme, and an example is in CustomizedMediaPicker in example project. Have a fantastic day!
