### ISSUE TITLE
Why did you stop supporting iOS 15?

### ISSUE THREAD

**Issue by X901** [exyte/MediaPicker#20]
Hi,
I noticed a minimum support change from iOS 15 to iOS 16

I’m using it because I can fully customize it, and also because it supports iOS15 

as I check the library, everything is Suppourt iOS 15, you don’t use any new feature that is not available in iOS 15

**Comment by f3dm76** [comment]
Because of this https://github.com/exyte/MediaPicker/issues/13

**Comment by f3dm76** [comment]
Hey @X901 please try version 2.2.1, should be restored there. Have a nice day
