### ISSUE TITLE
Separate Camera & Photo Album permission requests.

### ISSUE THREAD

**Issue by chintan100** [exyte/MediaPicker#25]
I want to use MediaPicker for camera only but when we initialise MediaPicker, it asks for Photo Album permission as well. The code for photo album permission executes even if we want to only use camera. 

I feel code should be restructured so that when we want only camera access, only camera permissions should be asked and if we want photo album access, only photo album permissions should be asked.

**Comment by f3dm76** [comment]
Hey @chintan100, please check out version 2.2.3, have a great day!
