### ISSUE TITLE
`showFullscreenPreview = false` not selecting the picture

### ISSUE THREAD

**Issue by ferranconde** [exyte/MediaPicker#26]
Hi! Loving this package so far.

I'm using this picker from `ExyteChat`, and I'm passing the following options:

```swift
ChatView(messages: [])
.setMediaPickerSelectionParameters(MediaPickerParameters(mediaType: .photo, showFullscreenPreview: false))
```

However, when I disable `showFullscreenPreview`, when I tap on the photo, I see the photo gets immediately selected (good), and the picker is closed (good)... but the photo hasn't actually been added as an attachment, so I only have my text.

Could you please take a look at this? From the source code I can't see any obvious typo or anything like that.
Thanks!

**Comment by f3dm76** [comment]
Hey @ferranconde, thank you for reporting and for a clear problem description - I'll be sure to take a look as soon as I have a minute. Have a great day!

**Comment by f3dm76** [comment]
Hey @ferranconde, it was actually a chat issue - please check out ChatView version 1.3.6 and give it a go. And be sure to have a wonderful day!

**Comment by ferranconde** [comment]
@f3dm76 I did, and it's fixed! Thanks a lot for taking care of this :)
