### ISSUE TITLE
Feature Request: Direct Access to the Camera View

### ISSUE THREAD

**Issue by tsinis** [exyte/MediaPicker#33]
Hey Exyte Team!

First of all - thanks for a great media picker! This "issue" is not an issue :D but rather a feature request. Did you ever consider providing devs also direct `public` access to the `CameraViewModel` (so `CameraSelectionService`, `MediaPickerViewModel`, as well as any other necessary components)? This change would allow developers to directly access and use the `CustomCameraView/StandardConrolsCameraView` without navigating through the gallery view first. It will expand the usage options of the package and might help reduce coupling and improve modularization of it (as a side effect). Wdyt? Thanks!

BTW, looks like the picker supports not only [iOS 16](https://github.com/exyte/MediaPicker#requirements) but iOS 15 too, isn't it?

**Comment by f3dm76** [comment]
Hey @tsinis, thank you for your kind words, unfortunately we do not have time for open source right now. Making anything public complicates maintenance a lot, so no, I don't think we'll consider doing that, but you can always do a fork. 

 No, it doesn't - there is a bug with remote photos not working on 15th, which is too much to fix for amount of users who need it.

 Have a great day!
