### ISSUE TITLE
Custom filter for images

### ISSUE THREAD

**Issue by Jonovono** [exyte/MediaPicker#9]
I don't imagine this is supported, but what I am looking to do is be able to specify the images I want to load from the camera roll or a specific filter to filter based off of.

For example, I want to be able to run a `VNDetectHumanRectanglesRequest` or some other Request provided by Apple to filter what gets shown to the user before they select.

I would be willing to pay for this functionality if someone is up for it. It could be a custom fork of this library, whatever is easiest.

**Comment by nikita-afonasov** [comment]
Hello @Jonovono! Sorry for getting back to you only now, missed your message. Is this something that you still need?

**Comment by fukemy** [comment]
I think filtering image is needed everytimes for everyone

**Comment by f3dm76** [comment]
Hey @Jonovono and @fukemy, I've added the ability to pass a custom filtering closure, please check out version 1.2.1, have a wonderful day!
